---
- name: Make sure kitty configuration directoy exsists.
  file:
    path: "./home/{{ local_user }}/.config/kitty"
    state: directory
  tags: kitty

- name: Copy kitty configs.
  copy:
    src: kitty.conf
    dest: "/home/{{ local_user }}/.config/kitty"
  tags: kitty
