---
- name: Add docker repository
  become: true
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  tags: docker

- name: Install docker.
  become: true
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  tags: docker
