---
- name: Copy zshrc
  become: false
  copy:
    src: .zshrc
    dest: "/home/{{ local_user }}/.zshrc"
  tags: zsh

- name: Change user shell to zsh
  become: true
  user:
    name: "{{ local_user }}"
    shell: /bin/zsh
  tags: zsh
