---
- name: Create docker group.
  become: true
  group:
    name: docker
    state: present
  tags: docker

- name: Adding user {{ local_user }} to docker group.
  become: true
  user: name={{ local_user }}
        groups=docker
        append=yes
  tags: docker

- name: Add docker gpg key.
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags: docker

- name: Setup docker repo.
  become: true
  apt_repository:
    repo: https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install docker.
  become: true
  apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Start and enable docker service.
  systemd:
    state: started
    enabled: true
    name: docker
