---
- name: Make sure dnf config manager is installed.
  become: true
  dnf:
    name:
      - dnf-plugins-core
    state: latest

- name: Add github repository.
  become: true
  shell: "dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo"

- name: Install github cli.
  become: true
  dnf:
    name:
      - gh
