---
- name: Add github cli gpg key.
  become: true
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present

- name: Add github repo.
  become: true
  apt_repository:
    url: deb https://cli.github.com/packages bullseye stable
    state: present

- name: Install github cli.
  become: true
  apt:
    update_cache: true
    name:
      - gh
