---
- name: Add hashicorp gpg key.
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add hashicorp repository.
  become: true
  apt_repository:
    repo: deb https://apt.releases.hashicorp.com bullseye stable
    state: present

- name: Install hashicorp tools.
  become: true
  apt:
    update_cache: true
    name:
      - terraform
      - consul
      - packer
      - vagrant
      - vault
      - nomad
      - waypoint
      - boundary
