---
- name: Required packages to build from source.
  become: true
  apt:
    update_cache: true
    name:
      - make
      - meson
      - ninja-build
      - dh-autoreconf
      - libxcb-keysyms1-dev
      - libpango1.0-dev
      - libxcb-util0-dev
      - xcb
      - libxcb1-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libev-dev
      - libxcb-xkb-dev
      - libxcb-cursor-dev
      - libxkbcommon-dev
      - libxcb-xinerama0-dev
      - libxkbcommon-x11-dev
      - libstartup-notification0-dev
      - libxcb-randr0-dev
      - libxcb-xrm0
      - libxcb-xrm-dev
      - libxcb-shape0
      - libxcb-shape0-dev
    state: latest

- name: Create source code folder.
  become: true
  file:
    path: /tmp/i3-gaps
    state: directory

- name: Pull source code.
  become: true
  git:
    repo: 'https://github.com/Airblader/i3.git'
    dest: /tmp/i3-gaps

- name: Create build directory.
  become: true
  file:
    path: /tmp/i3-gaps/build
    state: directory

- name: Run meson.
  shell: meson --prefix /usr/local
  args:
    chdir: /tmp/i3-gaps/build

- name: Run ninja.
  shell: ninja
  args:
    chdir: /tmp/i3-gaps/build

- name: Run ninja.
  become: true
  shell: ninja install
  args:
    chdir: /tmp/i3-gaps/build

- name: Copy files to bin directory.
  become: true
  copy:
    src: /tmp/i3-gaps/build/i3
    dest: /usr/local/bin
    owner: root
    mode: "0755"

- name: Remove source code.
  file:
    state: absent
    path: /tmp/i3-gaps
