---
- name: Get sops latest release.
  github_release:
    user: mozilla
    repo: sops
    action: latest_release
  register: sops_release

- name: Print latest sops release.
  debug:
    msg: "Latest sops release is {{ sops_release.tag }}"

- name: Install sops.
  apt:
    deb: "https://github.com/mozilla/sops/releases/download/{{ sops_release.tag}}/sops_{{ sops_release.tag | replace('v', '')}}_amd64.deb"
    state: present
