---
- name: Add gpg key for microsoft repo
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  tags: vscode

- name: Add vscode repository into sources list
  become: true
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/code stable main
    state: present

- name: Add microsoft repository for vscode
  become: true
  apt:
    update_cache: true
    name: code
